version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Python requirements
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
