name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -e '.[tests]'
      - name: Tests
        run: ./checks.sh

  tests:
    name: "${{ matrix.os.emoji }} ${{ matrix.python.name }}"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - emoji: 🐧
            runs-on: [ubuntu-latest]
          - emoji: 🍎
            runs-on: [macos-latest]
          - emoji: 🪟
            runs-on: [windows-latest]
        python:
          - name: CPython 3.8
            runs-on: "3.8"
          - name: CPython 3.9
            runs-on: "3.9"
          - name: CPython 3.10
            runs-on: "3.10"
          - name: CPython 3.11
            runs-on: "3.11"
          - name: CPython 3.12
            runs-on: "3.12"
          - name: CPython 3.13
            runs-on: "3.13-dev"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.runs-on }}
          cache: pip
          check-latest: true
      - name: Install dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -e '.[tests]'
      - name: Tests
        run: python -m pytest

  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    needs: [quality, tests]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Automerge
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
