name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -e '.[tests]'
      - name: Tests
        run: ./checks.sh

  tests:
    name: "${{ matrix.os.emoji }} ${{ matrix.python.name }}"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - emoji: 🐧
            runs-on: [ubuntu-latest]
          - emoji: 🍎
            runs-on: [macos-latest]
          - emoji: 🪟
            runs-on: [windows-latest]
        python:
          - name: CPython 3.8
            runs-on: "3.8"
          - name: CPython 3.9
            runs-on: "3.9"
          - name: CPython 3.10
            runs-on: "3.10"
          - name: CPython 3.11
            runs-on: "3.11"
          # Following are disabled because of https://github.com/ethereum/eth-tester/issues/276
          # - name: CPython 3.12
          #   runs-on: "3.12"
          # Waaaay to soon for 3.13
          # - name: CPython 3.13-dev
          #   runs-on: "3.13-dev"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.runs-on }}
          cache: pip
          check-latest: true
      - name: Install dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -e '.[tests]'
      - name: Tests
        run: python -m pytest
